# Generated by Django 2.2.17 on 2020-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201212_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
