# Generated by Django 2.2.17 on 2020-12-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201212_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, upload_to='products/', verbose_name='Фото'),
        ),
    ]
