# Generated by Django 2.2.17 on 2021-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Видимость'),
        ),
    ]
