# Generated by Django 2.2.17 on 2021-01-15 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210115_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 15, 59, 54, 330884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/user_avatars/4x4.jpg', upload_to='user_avatars', verbose_name='Аватар'),
        ),
    ]
