# Generated by Django 2.2.17 on 2021-01-18 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210119_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 21, 49, 54, 150170, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='birthday',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='День рождения'),
        ),
    ]
