# Generated by Django 2.2.17 on 2021-01-19 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20210119_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 22, 46, 22, 244064, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/4x4.jpg', upload_to='user_avatars', verbose_name='Аватар'),
        ),
    ]
